export const SCENE_LAYERS = [
  {
    id: 'sun',
    src: '/scene/sun-gold.png',
    size: 18,
    left: '2%',
    bottom: '72%',
    parallax: 0.08,
    anim: 'pulse',
    duration: 6,
  },
  {
    id: 'cloud-far',
    src: '/scene/cloud-far.png',
    size: 22,
    left: '52%',
    bottom: '78%',
    parallax: 0.1,
    anim: 'drift',
    duration: 34,
  },
  {
    id: 'cloud-near',
    src: '/scene/cloud-near.png',
    size: 30,
    left: '6%',
    bottom: '60%',
    parallax: 0.16,
    anim: 'drift',
    duration: 26,
    reverse: true,
  },
  {
    id: 'mountain-far',
    src: '/scene/mountain-far.png',
    size: 125,
    left: '-12%',
    bottom: '8%',
    parallax: 0.2,
    anim: 'none',
  },
  {
    id: 'mountain-mid',
    src: '/scene/mountain-mid.png',
    size: 135,
    left: '-18%',
    bottom: '2%',
    parallax: 0.32,
    anim: 'none',
  },
  {
    id: 'queuna-1',
    src: '/scene/queuna-1.png',
    size: 30,
    left: '2%',
    bottom: '6%',
    parallax: 0.44,
    anim: 'sway',
    duration: 5,
  },
  {
    id: 'queuna-2',
    src: '/scene/queuna-2.png',
    size: 38,
    left: '66%',
    bottom: '4%',
    parallax: 0.54,
    anim: 'sway',
    duration: 6.5,
  },
  {
    id: 'cactus',
    src: '/scene/cactus-silueste.png',
    size: 14,
    left: '58%',
    bottom: '14%',
    parallax: 0.36,
    anim: 'none',
  },
  {
    id: 'grass-ichu',
    src: '/scene/grass-ichu.png',
    size: 90,
    left: '5%',
    bottom: '0%',
    parallax: 0.62,
    anim: 'wave',
    duration: 3.6,
  },
  {
    id: 'grass-edge',
    src: '/scene/grass-edge.png',
    size: 110,
    left: '-5%',
    bottom: '-3%',
    parallax: 0.78,
    anim: 'sway',
    duration: 4.2,
  },
  {
    id: 'condor',
    src: '/scene/condor.png',
    size: 9,
    left: '40%',
    bottom: '86%',
    parallax: 0.55,
    anim: 'drift',
    duration: 22,
  },
  {
    id: 'star',
    src: '/scene/star-gold.png',
    size: 6,
    left: '30%',
    bottom: '90%',
    parallax: 0.1,
    anim: 'twinkle',
    duration: 3,
  },
];
